default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: employee_management
  password: 0908251534

development:
  <<: *default
  database: ApiEmployeeManagement_development

test:
  <<: *default
  database: ApiEmployeeManagement_test

production:
  <<: *default
  database: ApiEmployeeManagement_production
  username: ApiEmployeeManagement
  password: <%= ENV['API_EMPLOYEES_MANAGEMENT_PASSWORD'] %>
